[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[profile.default.remappings]
"@openzeppelin/contracts-upgradeable/" = "lib/openzeppelin-contracts-upgradeable/contracts/"
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"@chainlink/" = "lib/chainlink-brownie-contracts/contracts/"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
